AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to set up an S3-triggered Glue ETL workflow

Parameters:
  DataBucket1Name:
    Type: String
    Description: Name of the first S3 bucket
    Default: scriptbucketkuangju87
    
  DataBucket2Name:
    Type: String
    Description: Name of the second S3 bucket
    Default: databucketkuangju87
    
  # EMRClusterId parameter commented out since we're not using EMR
  # EMRClusterId:
  #   Type: String
  #   Description: EMR Cluster ID
  #   Default: j-XXXXXXXXXXXXX

Resources:
  # IAM Role for Glue
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DataBucket1Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket1Name}/*'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}/*'

  # Glue ETL Job
  GlueETLJob:
    Type: AWS::Glue::Job
    DependsOn: GlueServiceRole
    Properties:
      Name: MyGlueETLJob
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${DataBucket1Name}/glue-etl-script.py'
        PythonVersion: '3'
      DefaultArguments:
        '--TempDir': !Sub 's3://${DataBucket1Name}/temp/'
        '--job-bookmark-option': 'job-bookmark-enable'
        '--ENV_INPUT_BUCKET': !Ref DataBucket2Name
        '--ENV_OUTPUT_BUCKET': !Ref DataBucket1Name
        '--job-language': 'python'
        '--enable-metrics': 'true'
      GlueVersion: '2.0'
      WorkerType: G.1X
      NumberOfWorkers: 2
      MaxRetries: 0

  # IAM Role for Step Functions (Simplified - removed EMR permissions)
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: GlueETLJob
    Properties:
      RoleName: StepFunctionsExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsGluePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                  - glue:BatchStopJobRun
                Resource: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/*'
        # EMR permissions commented out since we're not using EMR
        # - PolicyName: StepFunctionsEMRPolicy
        #   PolicyDocument:
        #     Version: '2012-10-17'
        #     Statement:
        #       - Effect: Allow
        #         Action:
        #           - elasticmapreduce:RunJobFlow
        #           - elasticmapreduce:DescribeCluster
        #           - elasticmapreduce:ListSteps
        #           - elasticmapreduce:AddJobFlowSteps
        #           - elasticmapreduce:DescribeStep
        #           - elasticmapreduce:CancelSteps
        #         Resource: "*"
        - PolicyName: StepFunctionsS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DataBucket1Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket1Name}/*'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}/*'

  # Step Functions State Machine - Glue Only Workflow
  # Note: SparkJob2 is disabled. To enable later:

  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    DependsOn: 
      - StepFunctionsExecutionRole
      - GlueETLJob
    Properties:
      StateMachineName: GlueWorkflow
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "A simple AWS Step Functions state machine that executes Glue jobs.",
          "StartAt": "GlueJob1",
          "States": {
            "GlueJob1": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun.sync",
              "Parameters": {
                "JobName": "MyGlueETLJob",
                "Arguments": {
                  "--job-bookmark-option": "job-bookmark-enable",
                  "--TempDir": "s3://${DataBucket1Name}/temp/"
                }
              },
              "End": true,
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "JobFailed"
                }
              ]
            },
            "JobFailed": {
              "Type": "Fail",
              "Cause": "Job execution failed",
              "Error": "WorkflowFailed"
            }
          }
        }

Outputs:
  GlueETLJobName:
    Description: The Glue ETL Job Name
    Value: !Ref GlueETLJob
    Export:
      Name: MyGlueETLJob

  StateMachineArn:
    Description: The ARN of the Step Functions State Machine
    Value: !Ref MyStateMachine
    Export:
      Name: MyStateMachineArn

  GlueServiceRoleArn:
    Description: IAM Role for Glue Service
    Value: !GetAtt GlueServiceRole.Arn
    Export:
      Name: GlueServiceRoleArn

  StepFunctionsRoleArn:
    Description: IAM Role for Step Functions
    Value: !GetAtt StepFunctionsExecutionRole.Arn
    Export:
      Name: StepFunctionsRoleArn