AWSTemplateFormatVersion: '2010-09-09'
Description: S3-triggered Lambda to Aurora PostgreSQL (Fixed for Free Plan Express Configuration)

Parameters:
  RDSSecretArn:
    Type: String
    NoEcho: true
  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
  DatabaseName:
    Type: String
    Default: MyDatabase
  TableName:
    Type: String
    Default: uploaded_data
  DataBucket1Name:
    Type: String
    Default: scriptbucketkuangju87
  DataBucket2Name:
    Type: String
    Default: databucketkuangju87
  VPCId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  StateMachineArn:
    Type: String

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VPCId

  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from Lambda to Aurora PG
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !GetAtt LambdaSecurityGroup.GroupId

  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora
      SubnetIds: !Ref PrivateSubnetIds

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub "aurora-cluster-${AWS::StackName}"
      Engine: aurora-postgresql
      EngineVersion: "15.4"
      EngineMode: provisioned # REQUIRED for Express Configuration
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Sub '{{resolve:secretsmanager:${RDSSecretArn}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RDSSecretArn}:SecretString:password}}'
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt AuroraSecurityGroup.GroupId
      BackupRetentionPeriod: 1
      StorageEncrypted: true
      # This block satisfies the 'WithExpressConfiguration' requirement
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1.0

  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "aurora-instance-${AWS::StackName}"
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-postgresql
      PubliclyAccessible: false

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: RDSPostgresDependencies
      Content:
        S3Bucket: !Ref DataBucket1Name
        S3Key: dependencies_package.zip
      CompatibleRuntimes: [python3.9]

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [s3:GetObject, s3:ListBucket]
                Resource: 
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}/*'
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [secretsmanager:GetSecretValue]
                Resource: !Ref RDSSecretArn

  TriggerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: S3ToAuroraLoader
      Handler: lambda_stepfunction.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Layers: [!Ref LambdaLayer]
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: !Ref PrivateSubnetIds
      Environment:
        Variables:
          RDS_SECRET_ARN: !Ref RDSSecretArn
          DATABASE_NAME: !Ref DatabaseName
          TABLE_NAME: !Ref TableName
          STATE_MACHINE_ARN: !Ref StateMachineArn
          RDS_CLUSTER_ENDPOINT: !GetAtt AuroraCluster.Endpoint.Address
      Code:
        S3Bucket: !Ref DataBucket1Name
        S3Key: lambda_stepfunction.py

  S3LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TriggerLambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${DataBucket2Name}'

Outputs:
  LambdaFunctionArn:
    Value: !GetAtt TriggerLambdaFunction.Arn