AWSTemplateFormatVersion: '2010-09-09'
Description: S3-triggered Lambda to RDS PostgreSQL (Standard Free Tier Eligible)

Parameters:
  RDSSecretArn:
    Type: String
    NoEcho: true
  DBInstanceClass:
    Type: String
    Default: db.t4g.micro # Standard Free Tier Instance
  DatabaseName:
    Type: String
    Default: MyDatabase
  TableName:
    Type: String
    Default: uploaded_data
  DataBucket1Name:
    Type: String
    Default: scriptbucketkuangju87
  DataBucket2Name:
    Type: String
    Default: databucketkuangju87
  VPCId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  StateMachineArn:
    Type: String

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VPCId

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from Lambda to RDS PG
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !GetAtt LambdaSecurityGroup.GroupId

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: !Ref PrivateSubnetIds

  # Changed from AuroraCluster to a Single RDS Instance for Free Tier eligibility
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "rds-instance-${AWS::StackName}"
      Engine: postgres
      EngineVersion: "16.3" # Stable RDS version
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: "20" # 20GB is the Free Tier limit
      DBName: !Ref DatabaseName
      MasterUsername: !Sub '{{resolve:secretsmanager:${RDSSecretArn}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RDSSecretArn}:SecretString:password}}'
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      StorageEncrypted: true

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: RDSPostgresDependencies
      Content:
        S3Bucket: !Ref DataBucket1Name
        S3Key: dependencies_package.zip
      CompatibleRuntimes: [python3.9]

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [s3:GetObject, s3:ListBucket]
                Resource: 
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}/*'
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [secretsmanager:GetSecretValue]
                Resource: !Ref RDSSecretArn

  TriggerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: S3ToAuroraLoader
      Handler: lambda_stepfunction.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Layers: [!Ref LambdaLayer]
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: !Ref PrivateSubnetIds
      Environment:
        Variables:
          RDS_SECRET_ARN: !Ref RDSSecretArn
          DATABASE_NAME: !Ref DatabaseName
          TABLE_NAME: !Ref TableName
          STATE_MACHINE_ARN: !Ref StateMachineArn
          # Updated to use the RDS Instance Endpoint
          RDS_CLUSTER_ENDPOINT: !GetAtt RDSInstance.Endpoint.Address
      Code:
        S3Bucket: !Ref DataBucket1Name
        S3Key: lambda_stepfunction.py

  S3LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TriggerLambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${DataBucket2Name}'

Outputs:
  LambdaFunctionArn:
    Value: !GetAtt TriggerLambdaFunction.Arn
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address