AWSTemplateFormatVersion: '2010-09-09'
Description: S3-triggered Lambda to load data into RDS and trigger Step Functions

Parameters:
  # REMOVED: MasterUsername and MasterUserPassword parameters
  
  # ADDED: Secret ARN parameter (pre-created secret)
  RDSSecretArn:
    Type: String
    Description: ARN of the pre-created Secrets Manager secret containing RDS credentials
    NoEcho: true
    
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      
  DBAllocatedStorage:
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 100

  DatabaseName:
    Type: String
    Default: MyDatabase
    Description: Name of the RDS database
    
  TableName:
    Type: String
    Default: UploadedData
    Description: Name of the table to store S3 data

  DataBucket1Name:
    Type: String
    Default: scriptbucketkuangju87
    Description: Bucket for scripts/lambda code
    
  DataBucket2Name:
    Type: String
    Default: databucketkuangju87
    Description: Bucket for data files (CSV uploads)
  
  # NEW: Add these parameters
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for resources
    
  PrivateSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet ID for RDS and Lambda
    
  StateMachineArn:
    Type: String
    Description: ARN of the Step Functions state machine


Resources:
  # Security Group for RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from Lambda to RDS
      VpcId: !Ref VPCId  # CHANGED: !Ref instead of !ImportValue
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16

  # Security Group for Lambda
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VPCId  # CHANGED: !Ref instead of !ImportValue

  # RDS Subnet Group
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      DBSubnetGroupName: MyDBSubnetGroup
      SubnetIds:
        - !Ref PrivateSubnetId  # CHANGED: !Ref instead of !ImportValue

  # RDS Instance - Uses pre-created secret
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: 
      - RDSSubnetGroup
    Properties:
      DBInstanceIdentifier: MyRDSDatabase
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      DBName: !Ref DatabaseName
      Engine: mysql
      EngineVersion: "8.0.35"
      # ✅ Uses dynamic references to pre-created secret
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecretArn, ':SecretString:username}}']]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecretArn, ':SecretString:password}}']]
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: false
      StorageType: gp2
      BackupRetentionPeriod: 7
      MultiAZ: false
      Tags:
        - Key: ManagedBy
          Value: CloudFormation

  # S3 Bucket for Data
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataBucket2Name
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
            Function: !GetAtt TriggerLambdaFunction.Arn

  # Lambda Layer for Dependencies
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: RDSPythonDependencies
      Description: Layer with pymysql and other dependencies
      Content:
        S3Bucket: !Ref DataBucket1Name
        S3Key: dependencies_package.zip
      CompatibleRuntimes:
        - python3.8
        - python3.9
        - python3.10

  # IAM Role for Lambda Function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3toRDSLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}/*'
        - PolicyName: StepFunctionsAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref StateMachineArn  # CHANGED: !Ref instead of !ImportValue
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Ref RDSSecretArn
        - PolicyName: RDSConnectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-db:connect
                Resource: !Sub 'arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:*/*'
        - PolicyName: RDSDescribePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds:DescribeDBInstances
                Resource: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${RDSInstance}'

  # Lambda Function
  TriggerLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: 
      - LambdaExecutionRole
      - LambdaLayer
      - RDSInstance
    Properties:
      FunctionName: S3ToRDSLoader
      Description: Loads CSV data from S3 into RDS and triggers Step Functions
      Handler: lambda_stepfunction.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 300
      MemorySize: 1024
      Layers:
        - !Ref LambdaLayer
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetId  # CHANGED: !Ref instead of !ImportValue
      Environment:
        Variables:
          RDS_SECRET_ARN: !Ref RDSSecretArn  # ✅ Uses secret ARN parameter
          DATABASE_NAME: !Ref DatabaseName
          TABLE_NAME: !Ref TableName
          STATE_MACHINE_ARN:  !Ref StateMachineArn  # CHANGED: !Ref instead of !ImportValue
          RDS_INSTANCE_ID: !Ref RDSInstance
      Code:
        S3Bucket: !Ref DataBucket1Name
        S3Key: lambda_stepfunction.py

  # Lambda Permission for S3
  S3LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TriggerLambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:s3:::${DataBucket2Name}'

Outputs:
  RDSInstanceEndpoint:
    Description: Endpoint of the RDS Instance
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: MyRDSInstanceEndpoint

  RDSInstanceId:
    Description: RDS Instance Identifier
    Value: !Ref RDSInstance
    Export:
      Name: MyRDSInstanceId

  LambdaFunctionArn:
    Description: ARN of the Lambda Function
    Value: !GetAtt TriggerLambdaFunction.Arn
    Export:
      Name: S3toRDSLambdaArn

  DataBucketName:
    Description: Name of the S3 data bucket
    Value: !Ref DataBucket2Name
    Export:
      Name: DataBucketName

  LambdaSecurityGroupId:
    Description: Security Group ID for Lambda
    Value: !GetAtt LambdaSecurityGroup.GroupId
    Export:
      Name: LambdaSecurityGroupId