AWSTemplateFormatVersion: '2010-09-09'
Description: S3-triggered Lambda to load data into Aurora MySQL and trigger Step Functions

Parameters:
  RDSSecretArn:
    Type: String
    Description: ARN of the pre-created Secrets Manager secret
    NoEcho: true
    
  DBInstanceClass:
    Type: String
    Default: db.t3.medium
    AllowedValues: [db.t3.medium, db.r5.large, db.r6g.large]
      
  DatabaseName:
    Type: String
    Default: MyDatabase
    
  TableName:
    Type: String
    Default: UploadedData

  DataBucket1Name:
    Type: String
    Default: scriptbucketkuangju87
    
  DataBucket2Name:
    Type: String
    Default: databucketkuangju87
  
  VPCId:
    Type: AWS::EC2::VPC::Id
    
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    
  StateMachineArn:
    Type: String
    Description: ARN of the Step Functions state machine

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VPCId

  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from Lambda to Aurora
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt LambdaSecurityGroup.GroupId

  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora
      SubnetIds: !Ref PrivateSubnetIds

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub "aurora-cluster-${AWS::StackName}"
      Engine: aurora-mysql
      EngineVersion: "8.0.mysql_aurora.3.05.2"
      DatabaseName: !Ref DatabaseName
      # FIXED: Using !Sub for Dynamic Reference string construction
      MasterUsername: !Sub '{{resolve:secretsmanager:${RDSSecretArn}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RDSSecretArn}:SecretString:password}}'
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt AuroraSecurityGroup.GroupId
      BackupRetentionPeriod: 7
      StorageEncrypted: true

  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "aurora-instance-${AWS::StackName}"
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  DataBucket:
    Type: AWS::S3::Bucket
    DependsOn: S3LambdaPermission
    Properties:
      BucketName: !Ref DataBucket2Name
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
            Function: !GetAtt TriggerLambdaFunction.Arn

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: RDSPythonDependencies
      Content:
        S3Bucket: !Ref DataBucket1Name
        S3Key: dependencies_package.zip
      CompatibleRuntimes: [python3.8, python3.9, python3.10]

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [s3:GetObject, s3:ListBucket]
                Resource: 
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}'
                  - !Sub 'arn:aws:s3:::${DataBucket2Name}/*'
        - PolicyName: StepFunctionsAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref StateMachineArn
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [secretsmanager:GetSecretValue]
                Resource: !Ref RDSSecretArn

  TriggerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: S3ToAuroraLoader
      Handler: lambda_stepfunction.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 300
      Layers: [!Ref LambdaLayer]
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: !Ref PrivateSubnetIds
      Environment:
        Variables:
          RDS_SECRET_ARN: !Ref RDSSecretArn
          DATABASE_NAME: !Ref DatabaseName
          TABLE_NAME: !Ref TableName
          STATE_MACHINE_ARN: !Ref StateMachineArn
          RDS_CLUSTER_ENDPOINT: !GetAtt AuroraCluster.Endpoint.Address
      Code:
        S3Bucket: !Ref DataBucket1Name
        S3Key: lambda_stepfunction.py

  S3LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TriggerLambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${DataBucket2Name}'

Outputs:
  AuroraClusterEndpoint:
    Value: !GetAtt AuroraCluster.Endpoint.Address
  LambdaFunctionArn:
    Value: !GetAtt TriggerLambdaFunction.Arn